task_id:"aLn8NVGqnnZ0PjqsWtFWQ"  situation_id:"MQveyySzo9iNmTEgKjKyr"  check_item:{check_item_id:"3RFrrZy89fqmYp8VIYZAX"  command:{command_id:"VmgIV2eoCc3FreS3aLH8u"  command_line:"progate diagnose"}}  check_item:{check_item_id:"QVX4c2niXk3aJ2vU_8zA5"  command:{command_id:"hAUjDWg7HJFD3dhg80YQG"  command_line:"node test/judge_largest_change_date.js"}}